### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by ResistanceIsUseless** [projectdiscovery/retryablehttp-go#1]
Do you plan on adding any examples on how best to use this? Are there any key differences between yours and the one from hashicorp? I have an idea for something i want to build but it's hard to know which package to use.

**Comment by Mzack9999** [comment]
@ResistanceIsUseless - The library is very similar to the hashicorp one as mentioned in the readme file. Here we handle more edge case where both the standard library and hashicorp one fails (we created a separate subproject to track the edge cases and that we use for tests at https://github.com/projectdiscovery/retryablehttp-go/tree/master/buggyhttp). Also we added some functionalities like request metrics, and default profiles aimed at maximizing connection reuse or, as opposite, connection termination in case of mass scanning (for example one issue of the standard `net/http` is that it creates a lot of idle connections causing outage of file descriptors). For sure we will need to write detailed documentation and examples.
