### ISSUE TITLE
[Vulnerability] Advice on progress in handling the vulnerability report

### ISSUE THREAD

**Issue by zer0yu** [projectdiscovery/retryablehttp-go#250]
I am writing to follow up on the vulnerability report I submitted to your email address as per the vulnerability disclosure policy outlined in Security.md. As of now, I have not received a response confirming the receipt of my email.

I would greatly appreciate it if you could verify whether my vulnerability report has been correctly received. If there are any issues or if you require any additional information from me, please let me know.

Thank you for your attention to this matter. I look forward to hearing back from you soon.

**Comment by toufik-airane** [comment]
Dear @zer0yu,

Thank you for reaching out to us via our vulnerability disclosure program.

To make sure I've been proceeding your reports as I can't identify you through your GitHub handle, are you k***2@gmail.com ?

Thank you.

**Comment by zer0yu** [comment]
Dear @toufik-airane 

Thank you for your response.

My email address is `vh**trx@gmail.com` , and the corresponding vulnerability report title is `The retryablehttp library may *** when malformed URLs are provided`.

**Comment by toufik-airane** [comment]
Sounds good. We've discussed it internally, and I've already sent you an email.

Let's proceed to close this canal unless there are additional details needed.

Thank you.
